"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { FollowsTransfer } from "@/components/follows-transfer";
type Library = { id: string; name: string };
type Service = { name: string; url: string; configured: boolean };
type Operations = { jobs: Record<string, { state: string; lastSuccessAt?: string; error?: string } | null>; freshness: Record<string, string | null> };
const labels: Record<string, string> = { "backup-db": "Database backup", "sync-komga": "Library sync", "refresh-releases": "Release refresh", "weekly-digest": "Weekly digest", "refresh-discover": "Discover refresh" };
function when(value?: string | null) { return value ? new Date(value).toLocaleString() : "Never"; }
function freshness(value: string | null | undefined, hours: number) { return value ? `${when(value)} (${Date.now() - new Date(value).getTime() > hours * 3600000 ? "stale" : "current"})` : "Never synced"; }
export function SettingsClient({ services, selectedLibrary, operations }: { services: Service[]; selectedLibrary: Library | null; operations: Operations }) {
  const [status, setStatus] = useState<Record<string, string>>({});
  const [libraries, setLibraries] = useState<Library[]>([]);
  const [selected, setSelected] = useState(selectedLibrary?.id ?? "");
  const [libraryMessage, setLibraryMessage] = useState<string | null>(null);
  const [running, setRunning] = useState<string | null>(null);
  const [operationMessage, setOperationMessage] = useState<string | null>(null);
  const router = useRouter();
  const test = async (name: string) => { setStatus((current) => ({ ...current, [name]: "Testing…" })); try { const response = await fetch(`/api/settings/${name.toLowerCase()}`, { method: "POST" }); const result = await response.json() as { message?: string }; setStatus((current) => ({ ...current, [name]: result.message ?? (response.ok ? "● Connected" : "○ Test failed") })); } catch { setStatus((current) => ({ ...current, [name]: "○ Could not reach the test endpoint" })); } };
  const loadLibraries = async () => { setLibraryMessage("Loading libraries…"); try { const response = await fetch("/api/settings/komga"); const result = await response.json() as { libraries?: Library[]; selectedLibraryId?: string | null; error?: string }; if (!response.ok) throw new Error(result.error ?? "Komga is not reachable"); setLibraries(result.libraries ?? []); setSelected(result.selectedLibraryId ?? selectedLibrary?.id ?? ""); setLibraryMessage(null); } catch (error) { setLibraryMessage(error instanceof Error ? error.message : "Komga is not reachable"); } };
  const saveLibrary = async () => { if (!selected) return; setLibraryMessage("Saving and syncing…"); try { const response = await fetch("/api/settings/komga", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ libraryId: selected }) }); const result = await response.json() as { error?: string }; if (!response.ok) throw new Error(result.error ?? "Could not save library"); setLibraryMessage("Selected library synced."); router.refresh(); } catch (error) { setLibraryMessage(error instanceof Error ? error.message : "Could not save library"); } };
  const run = async (name: "sync-komga" | "refresh-releases" | "backup-db") => { setRunning(name); setOperationMessage(name === "backup-db" ? "Backing up the database…" : name === "sync-komga" ? "Syncing your library…" : "Refreshing releases…"); try { const response = await fetch(`/api/jobs/${name}`, { method: "POST" }); const result = await response.json() as { error?: string; message?: string }; if (!response.ok) throw new Error(result.error ?? "Job failed"); setOperationMessage(result.message ?? "Finished."); router.refresh(); } catch (error) { setOperationMessage(`${error instanceof Error ? error.message : "Job failed"}. Check the connection above and retry.`); } finally { setRunning(null); } };
  return <div className="page"><h1 className="title">Settings</h1><section className="sec" style={{ marginTop: 24 }}><header><h2>Connections</h2></header>{services.map((service) => <div className="srow" key={service.name}><span>{service.name}</span><span className="muted u">{service.url}</span><span>{status[service.name] ?? (service.configured ? "Configured — test connection" : "○ Not configured")}</span><button className="lnk" disabled={!service.configured || status[service.name] === "Testing…"} onClick={() => void test(service.name)}>Test</button></div>)}</section><section className="sec"><header><h2>Komga library</h2><button onClick={() => void loadLibraries()}>Load libraries</button></header>{libraries.length ? <div className="tools"><select aria-label="Komga library" value={selected} onChange={(event) => setSelected(event.target.value)}><option value="">Choose a library</option>{libraries.map((library) => <option key={library.id} value={library.id}>{library.name}</option>)}</select><button onClick={() => void saveLibrary()} disabled={!selected || libraryMessage === "Saving and syncing…"}>Use this library</button></div> : selectedLibrary ? <p className="muted">Selected library: {selectedLibrary.name}. Load libraries to change it.</p> : <p className="muted">Load your Komga libraries, then choose the comics library. Gutter will exclude the others.</p>}{libraryMessage ? <p role="status" className="muted">{libraryMessage}</p> : null}</section><section className="sec"><header><h2>Data and jobs</h2></header>{Object.entries(labels).map(([key, label]) => <div className="srow" key={key}><span>{label}</span><span className="muted u">Last successful: {when(operations.jobs[key]?.lastSuccessAt)}</span><span>{operations.jobs[key]?.state === "failed" ? `○ Failed: ${operations.jobs[key]?.error}` : operations.jobs[key]?.state === "running" ? "Running…" : "● Ready"}</span>{key === "sync-komga" || key === "refresh-releases" || key === "backup-db" ? <button className="lnk" disabled={running !== null} onClick={() => void run(key)}>{running === key ? "Running…" : "Run now"}</button> : <span />}</div>)}<p className="muted">Library data: {freshness(operations.freshness["komga:series"], 1)} · Book data: {freshness(operations.freshness["komga:books"], 1)} · Discover: {freshness(operations.freshness["discover:recommendations"], 168)}</p>{operationMessage ? <p role="status" className="muted">{operationMessage}</p> : null}</section><FollowsTransfer /></div>;
}

